/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppBar: typeof import('./src/components/AppBar.vue')['default']
    Close: typeof import('./src/components/appbar/Close.vue')['default']
    Cropsquare: typeof import('./src/components/appbar/Cropsquare.vue')['default']
    ElPopover: typeof import('element-plus/es')['ElPopover']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    Language: typeof import('./src/components/appbar/Language.vue')['default']
    Minimize: typeof import('./src/components/appbar/Minimize.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Setting: typeof import('./src/components/appbar/Setting.vue')['default']
    Update: typeof import('./src/components/appbar/Update.vue')['default']
  }
}
